server:
  port: 9901
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${server.port}
management:
  server:
    port: ${server.port}
  security:
    enabled: false